name: AWS Terraform Provisioning

on:
  push:
    branches:
      - master

jobs:
  aws_terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-keypair-secret: ${{ secrets.AWS_KEYPAIR_SECRET }}
        aws-region: us-east-1

    - name: Terraform Init and Apply for AWS
      run: |
        cd aws
        terraform init
        terraform apply -target=data.aws_subnets.default_subnets -auto-approve
        terraform apply -auto-approve